### ISSUE TITLE
Better errors handling for edge cases

### ISSUE THREAD

**Issue by shimkiv** [o1-labs/zkapp-cli#255]
In certain cases the deployment might fail with the error like this:

```sh
> zk deploy berkeley

✔ Build project
✔ Generate build.json
✔ Choose smart contract
  The 'Add' smart contract will be used
  for this network as specified in config.json.
✔ Generate verification key (takes 10-30 sec)
✔ Build transaction
✔ Confirm to send transaction

  ┌────────────────┬─────────────────────────────────────────────────┐
  │ Network        │ berkeley                                        │
  ├────────────────┼─────────────────────────────────────────────────┤
  │ Url            │ https://proxy.berkeley.minaexplorer.com/graphql │
  ├────────────────┼─────────────────────────────────────────────────┤
  │ Smart Contract │ Add                                             │
  └────────────────┴─────────────────────────────────────────────────┘

  Are you sure you want to send (yes/no)? · yes
✔ Send to network
zk deploy [alias]

Deploy or redeploy a zkApp

Options:
  -y, --yes      Respond `yes` to all confirmation prompts.
                 Allows running non-interactively within a script.     [boolean]
  -h, --help     Show help                                             [boolean]
  -v, --version  Show version number                                   [boolean]

TypeError: errors.map is not a function
    at getErrorMessage (.../.nvm/versions/node/v16.15.1/lib/node_modules/zkapp-cli/src/lib/deploy.js:557:12)
    at deploy (.../.nvm/versions/node/v16.15.1/lib/node_modules/zkapp-cli/src/lib/deploy.js:416:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.handler (.../.nvm/versions/node/v16.15.1/lib/node_modules/zkapp-cli/src/bin/index.js:65:21)
```

Relevant discussion was held in O(1)'s internal [Slack channel](https://o1-labs.slack.com/archives/C028Q27R8UC/p1655289320086279).

**Comment by mitschabaude** [comment]
this is done
