### ISSUE TITLE
Problem when following the quick start example (error after entering network name)

### ISSUE THREAD

**Issue by smonev** [o1-labs/zkapp-cli#363]
### Describe the bug

Following the quick start example [here,](https://docs.minaprotocol.com/zkapps#quickstart) I get to the place to set a network and it returns an error. The same things happens when I try it natively on Windows, or on WSL2 (Ubuntu 20).

```
 user@DESKTOP-123  ~  node -v
v19.6.0
 user@DESKTOP-123  ~  npm -v
9.4.0
 user@DESKTOP-123  ~  cd .\mina\
 user@DESKTOP-123  ~  mina  npm install -g zkapp-cli

added 121 packages in 3m
npm notice
npm notice New patch version of npm available! 9.4.0 -> 9.4.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.4.2
npm notice Run npm install -g npm@9.4.2 to update!
npm notice
 user@DESKTOP-123  ~  mina  zk project mina_vox
✔ UI: Set up project
✔ Initialize Git repo
✔ Set up project
✔ NPM install
✔ NPM build contract
✔ Set project name
✔ Git init commit

Success!

Next steps:
  cd mina_vox
  git remote add origin <your-repo-url>
  git push -u origin main
 user@DESKTOP-123  ~  mina  cd .\mina_vox\
 user@DESKTOP-123  ~  mina  mina_vox  main  zk config

  ┌──────────────────────────────────┐
  │     Networks in config.json      │
  ├────────┬────────┬────────────────┤
  │ Name   │ Url    │ Smart Contract │
  ├────────┴────────┴────────────────┤
  │ None found                       │
  └──────────────────────────────────┘

Add a new network:
? Choose a name (can be anything): » testnet C:\Users\user\AppData\Roaming\nvm\v19.6.0\node_modules\zkapp-cli\src\lib\config.js:101
        if (Object.keys(config.networks).includes(val)) {
                   ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Input.validate (C:\Users\user\AppData\Roaming\nvm\v19.6.0\node_modules\zkapp-cli\src\lib\config.js:101:20)
    at Input.submit (C:\Users\user\AppData\Roaming\nvm\v19.6.0\node_modules\zkapp-cli\node_modules\enquirer\lib\prompt.js:123:49)
    at Input.submit (C:\Users\user\AppData\Roaming\nvm\v19.6.0\node_modules\zkapp-cli\node_modules\enquirer\lib\prompts\input.js:51:18)
    at Input.keypress (C:\Users\user\AppData\Roaming\nvm\v19.6.0\node_modules\zkapp-cli\node_modules\enquirer\lib\prompt.js:44:23)
    at Input.keypress (C:\Users\user\AppData\Roaming\nvm\v19.6.0\node_modules\zkapp-cli\node_modules\enquirer\lib\types\string.js:24:18)
    at ReadStream.on (C:\Users\user\AppData\Roaming\nvm\v19.6.0\node_modules\zkapp-cli\node_modules\enquirer\lib\keypress.js:205:26)
    at ReadStream.emit (node:events:524:35)
    at emitKeys (node:internal/readline/utils:357:14)
    at emitKeys.next (<anonymous>)

Node.js v19.6.0
```

### Steps to Reproduce

Details steps are in the description.

### System Info

```shell
Windows 10
WSL2 (Ubuntu 20) on Windows 10
```

### Severity

annoyance

**Comment by ymekuria** [comment]
Thanks for bringing this up @smonev . We will investigate further.

**Comment by smonev** [comment]
And here is the one from WSL2 (Ubuntu 20):

```
user@DESKTOP-123:~/mina/mina_vox(main)$ zk system
Please include the following when submitting a Github issue:

  System:
    OS: Linux 4.19 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  Binaries:
    Node: 16.11.1 - ~/.nvm/versions/node/v16.11.1/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.11.1/bin/npm
  npmPackages:
    snarkyjs: 0.8.0
  npmGlobalPackages:
    zkapp-cli: 0.6.2
```

**Comment by ymekuria** [comment]
Thanks for sharing this. @smonev try updating the cli version `npm update -g zkapp-cli`.

**Comment by smonev** [comment]
Running the update command resolved the issue @ymekuria, thank you.

**Comment by ymekuria** [comment]
> Running the update command resolved the issue @ymekuria, thank you.

I'm glad to hear that!
