### ISSUE TITLE
FIle Path misconfigured for --ui option with src/ directory enabled

### ISSUE THREAD

**Issue by ckartik** [o1-labs/zkapp-cli#379]
### Describe the bug

UI flag causes script to fail on misconfigured directory path to `pages/`, due to the selection of a src directory being added to the project.

The error that is communicated is: 
```bash
Error: ENOENT: no such file or directory, open 'ui/pages/index.tsx'
    at Object.openSync (node:fs:600:3)
    at Object.writeFileSync (node:fs:2221:35)
    at scaffoldNext (/Users/kartikchopra/.nvm/versions/node/v18.14.2/lib/node_modules/zkapp-cli/src/lib/project.js:483:6)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async project (/Users/kartikchopra/.nvm/versions/node/v18.14.2/lib/node_modules/zkapp-cli/src/lib/project.js:74:9)
    at async Object.handler (/Users/kartikchopra/.nvm/versions/node/v18.14.2/lib/node_modules/zkapp-cli/src/bin/index.js:56:21) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'ui/pages/index.tsx'
}
```

### Steps to Reproduce

Step 1. Create a project with the command
```bash 
$ zk project <prof-name> --ui=next
```

Step 2. When prompted with the question `✔ Would you like to use `src/` directory with this project? … No / Yes`, select Yes

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    Yarn: Not Found
    npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
  npmPackages:
    snarkyjs: Not Found (not in a project)
  npmGlobalPackages:
    zkapp-cli: 0.7.2
```

### Severity

serious, but I can work around it

**Comment by ckartik** [comment]
Looks like @ymekuria has fixed this [here](https://github.com/o1-labs/zkapp-cli/pull/378), 💯
