### ISSUE TITLE
Ui scaffolding fails for next if you check yes for ui scaffolding fails for next if you check yes for `Do you want to setup your project for deployment to Github Pages?`

### ISSUE THREAD

**Issue by ymekuria** [o1-labs/zkapp-cli#381]
### Describe the bug

The ui scaffolding fails for next if you check yes for `Do you want to setup your project for deployment to Github Pages?`

run zk project someproj --ui next and set yes for question.

`Do you want to setup your project for deployment to Github Pages? · no / yes`

### Steps to Reproduce

```
✔ Do you want your NextJS project to use TypeScript? · yes
✔ Do you want to setup your project for deployment to Github Pages? · yes
✔ Would you like to use ESLint with this project? … No / Yes
✔ Would you like to use experimental `app/` directory with this project? … No / Yes
Creating a new Next.js app in /ui.

Error: ENOENT: no such file or directory, open 'ui/pages/_app.page.tsx'
    at Object.openSync (node:fs:591:3)
    at Object.readFileSync (node:fs:459:35)
    at scaffoldNext (/opt/homebrew/lib/node_modules/zkapp-cli/src/lib/project.js:597:21)
    at async project (/opt/homebrew/lib/node_modules/zkapp-cli/src/lib/project.js:74:9)
    at async Object.handler (/opt/homebrew/lib/node_modules/zkapp-cli/src/bin/index.js:56:21) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'ui/pages/_app.page.tsx'
```

### System Info

```shell
System:
    OS: macOS 12.0.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 18.3.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - /opt/homebrew/bin/npm
  npmPackages:
    snarkyjs: 0.9.3
  npmGlobalPackages:
    zkapp-cli: 0.7.4
```

### Severity

serious, but I can work around it

**Comment by ymekuria** [comment]
Fixed with #382
