### ISSUE TITLE
Fails to complete NextJS project generation

### ISSUE THREAD

**Issue by shimkiv** [o1-labs/zkapp-cli#411]
- `zkapp-cli: 0.8.0`

```shell
zk project deploy-me
✔ Create an accompanying UI project too? · next
✔ Do you want to setup your project for deployment to Github Pages? · no
 Choose no to use experimental `app/` directory with this project
✔ Would you like to use TypeScript with this project? … No / Yes
✔ Would you like to use ESLint with this project? … No / Yes
✔ Would you like to use Tailwind CSS with this project? … No / Yes
✔ Use App Router (recommended)? … No / Yes
Creating a new Next.js app in /Users/shymkiv/projects/o1/zkapp-cli/deploy-me/ui.

Using npm.

Initializing project with template: app-tw


Installing dependencies:
- react
- react-dom
- next
- typescript
- @types/react
- @types/node
- @types/react-dom
- tailwindcss
- postcss
- autoprefixer
- eslint
- eslint-config-next


added 351 packages, and audited 352 packages in 7s

135 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Success! Created ui at /Users/shymkiv/projects/o1/zkapp-cli/deploy-me/ui

zk project [name]

Create a new project

Options:
      --ui       Creates an accompanying UI
                   [string] [choices: "next", "svelte", "nuxt", "empty", "none"]
  -h, --help     Show help                                             [boolean]
  -v, --version  Show version number                                   [boolean]

Error: ENOENT: no such file or directory, open 'ui/src/pages/index.tsx'
    at Object.openSync (node:fs:601:3)
    at Object.writeFileSync (node:fs:2249:35)
    at scaffoldNext (/usr/local/lib/node_modules/zkapp-cli/src/lib/project.js:493:6)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async project (/usr/local/lib/node_modules/zkapp-cli/src/lib/project.js:79:9)
    at async Object.handler (/usr/local/lib/node_modules/zkapp-cli/src/bin/index.js:55:21) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'ui/src/pages/index.tsx'
}
```

**Comment by ymekuria** [comment]
@shimkiv try to update your cli version. The app router feature is disabled in the current version and will be supported in the future. https://github.com/o1-labs/zkapp-cli/issues/400

**Comment by shimkiv** [comment]
@ymekuria thank you will try and close one then, not sure how I missed 0.8.2

**Comment by shimkiv** [comment]
Works well with 0.8.2, 0.9.0
