### ISSUE TITLE
Top Level Await not supported, Svelte Kit

### ISSUE THREAD

**Issue by 45930** [o1-labs/zkapp-cli#431]
### Describe the bug

In my own svelte kit app, I had this issue, but I found it behaves the same way in the example app.  If you run `npm run build` on the app, it will start to compile, then fail and spit out:

```
✓ built in 56.38s
error during build:
Error: Transform failed with 1 error:
_app/immutable/chunks/index.!~{00e}~.js:2200:1930: ERROR: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)
    at failureErrorWithLog (/Users/me/Projects/zkapps/svelte-test/ui/node_modules/esbuild/lib/main.js:1636:15)
    at /Users/me/Projects/zkapps/svelte-test/ui/node_modules/esbuild/lib/main.js:837:29
    at responseCallbacks.<computed> (/Users/me/Projects/zkapps/svelte-test/ui/node_modules/esbuild/lib/main.js:697:9)
    at handleIncomingPacket (/Users/me/Projects/zkapps/svelte-test/ui/node_modules/esbuild/lib/main.js:752:9)
    at Socket.readFromStdout (/Users/me/Projects/zkapps/svelte-test/ui/node_modules/esbuild/lib/main.js:673:7)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

### Steps to Reproduce

`zk p svelte-example`

Close the parenthesis in the last line of `ui/vite.config.js` ;)

`npm run build`

### System Info

```shell
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 9.6.4 - ~/.nvm/versions/node/v16.14.2/bin/npm
  npmPackages:
    snarkyjs: 0.* => 0.11.0 
  npmGlobalPackages:
    zkapp-cli: 0.7.5
```
```


### Severity

serious, but I can work around it

### Additional Information

_No response_

**Comment by ymekuria** [comment]
Thanks for bringing this up @45930. Try updating your cli version. The current version is `0.9.0` and the UI project scaffolds were configured to support top level await in v `0.8.0`  after [this pr](https://github.com/o1-labs/zkapp-cli/pull/399).
