### ISSUE TITLE
Impossible to generate Nuxt project

### ISSUE THREAD

**Issue by shimkiv** [o1-labs/zkapp-cli#449]
```shell
~/projects/o1/zkapp-cli   e2e-tests ±  zk project  deploy-me
✔ Create an accompanying UI project too? · nuxt
Nuxi 3.4.0                                                                                                                                  7:04:11 PM
✨ Nuxt project is created with v3 template. Next steps:                                                                                    7:04:12 PM
 › cd ui                                                                                                                                    7:04:12 PM
 › Install dependencies with npm install or yarn install or pnpm install                                                                    7:04:12 PM
 › Start development server with npm run dev or yarn dev or pnpm run dev                                                                    7:04:12 PM
✔ UI: Set up project
✖ UI: NPM install
 ✘  ~/projects/o1/zkapp-cli   e2e-tests ±  cd deploy-me/
 ~/projects/o1/zkapp-cli/deploy-me   e2e-tests ±  ll
total 0
drwxr-xr-x   3 serhii  staff   96 Jul  7 19:04 .
drwxr-xr-x  29 serhii  staff  928 Jul  7 19:04 ..
drwxrwxr-x  16 serhii  staff  512 Jul  7 19:04 ui
 ~/projects/o1/zkapp-cli/deploy-me   e2e-tests ±  cd ui
 ~/projects/o1/zkapp-cli/deploy-me/ui   e2e-tests ±  npm install

> postinstall
> nuxt prepare

Nuxi 3.6.2                                                                                                                                  7:05:16 PM

 ERROR  ParseError: Unexpected token, expected ","                                                                                          7:05:17 PM
 /Users/shymkiv/projects/o1/zkapp-cli/deploy-me/ui/nuxt.config.ts:12:2

  nuxt.config.ts:12:2
  at resolveConfig (node_modules/c12/dist/index.mjs:280:24)
  at loadConfig (node_modules/c12/dist/index.mjs:116:40)
  at async loadNuxtConfig (node_modules/@nuxt/kit/dist/index.mjs:2483:18)
  at async loadNuxt (node_modules/nuxt/dist/index.mjs:3269:19)
  at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:2537:19)
  at async Object.invoke (node_modules/nuxi/dist/chunks/prepare.mjs:31:18)
  at async _main (node_modules/nuxi/dist/cli.mjs:49:20)

npm ERR! code 1
npm ERR! path /Users/shymkiv/projects/o1/zkapp-cli/deploy-me/ui
npm ERR! command failed
npm ERR! command sh -c nuxt prepare

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shymkiv/.npm/_logs/2023-07-07T16_05_15_030Z-debug-0.log
 ✘  ~/projects/o1/zkapp-cli/deploy-me/ui   e2e-tests ±  zk -v
0.10.1
```

**Comment by shimkiv** [comment]
```shell
cat /Users/shymkiv/projects/o1/zkapp-cli/deploy-me/ui/nuxt.config.ts
// https://nuxt.com/docs/api/configuration/nuxt-config

  export default defineNuxtConfig({

    vite: {
      build: { target: "esnext" },
      optimizeDeps: { esbuildOptions: { target: "esnext" } },
    },

    css: ['~/assets/styles/globals.css'] // <- , is required

  devtools: { enabled: true }
})
```
